[package]
name = "mrse"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"
lto = "fat"

[dependencies]
flate2 = { version = "1.0", features = ["zlib-ng"] }
crc32fast = "1.4"
walkdir = "2.5"
